sq = ('\'spam eggs\'')
print(sq)
dq = ('\"spam eggs\"')
print(dq)
sq1 = ('doesn\'t')
print(sq1)
dq1 =("doesn't")
print(dq1)
sq2 = ('"Yes," they said.')
print(sq2)
dq2 = ("\"Yes,\" they said.")
print(dq2)
dq3 = ('"Isn\'t," they said.')
print(dq3)
